# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m

# AndroidX
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=false

# Performance
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

# Workaround for kapt compatibility with AGP 9.0
android.builtInKotlin=false
android.newDsl=false
